[tool.isort]
multi_line_output = 3
include_trailing_comma = true
skip = ['unparser.py']

[tool.cercis]
wrap-line-with-long-string = true
extend-exclude = 'tests/data'

[tool.pydoclint]
style = 'numpy'
exclude = '\.git|.?venv|\.tox|tests/data|unparser\.py'
require-return-section-when-returning-nothing = true
